#!/bin/bash
set -e

DEST=$1

go build -x -v \
	-o "$DEST/docker-$VERSION" \
	"${BUILDFLAGS[@]}" \
    -gccgoflags "
        -static-libgo -static-libgcc -v -Wl,-t
	" \
	./docker
echo "Created binary: $DEST/docker-$VERSION"
ln -sf "docker-$VERSION" "$DEST/docker"

hash_files "$DEST/docker-$VERSION"
